// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nestedfield.proto

package io.confluent.connect.protobuf.test;

public final class NestedKeyValue {
  private NestedKeyValue() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface NestedKeyValueMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:NestedKeyValueMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.AttributeFieldEntry field1 = 1;</code>
     * @return Whether the field1 field is set.
     */
    boolean hasField1();
    /**
     * <code>.AttributeFieldEntry field1 = 1;</code>
     * @return The field1.
     */
    io.confluent.connect.protobuf.test.NestedKeyValue.AttributeFieldEntry getField1();
    /**
     * <code>.AttributeFieldEntry field1 = 1;</code>
     */
    io.confluent.connect.protobuf.test.NestedKeyValue.AttributeFieldEntryOrBuilder getField1OrBuilder();
  }
  /**
   * Protobuf type {@code NestedKeyValueMessage}
   */
  public static final class NestedKeyValueMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:NestedKeyValueMessage)
      NestedKeyValueMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use NestedKeyValueMessage.newBuilder() to construct.
    private NestedKeyValueMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NestedKeyValueMessage() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new NestedKeyValueMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.confluent.connect.protobuf.test.NestedKeyValue.internal_static_NestedKeyValueMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.confluent.connect.protobuf.test.NestedKeyValue.internal_static_NestedKeyValueMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.confluent.connect.protobuf.test.NestedKeyValue.NestedKeyValueMessage.class, io.confluent.connect.protobuf.test.NestedKeyValue.NestedKeyValueMessage.Builder.class);
    }

    public static final int FIELD1_FIELD_NUMBER = 1;
    private io.confluent.connect.protobuf.test.NestedKeyValue.AttributeFieldEntry field1_;
    /**
     * <code>.AttributeFieldEntry field1 = 1;</code>
     * @return Whether the field1 field is set.
     */
    @java.lang.Override
    public boolean hasField1() {
      return field1_ != null;
    }
    /**
     * <code>.AttributeFieldEntry field1 = 1;</code>
     * @return The field1.
     */
    @java.lang.Override
    public io.confluent.connect.protobuf.test.NestedKeyValue.AttributeFieldEntry getField1() {
      return field1_ == null ? io.confluent.connect.protobuf.test.NestedKeyValue.AttributeFieldEntry.getDefaultInstance() : field1_;
    }
    /**
     * <code>.AttributeFieldEntry field1 = 1;</code>
     */
    @java.lang.Override
    public io.confluent.connect.protobuf.test.NestedKeyValue.AttributeFieldEntryOrBuilder getField1OrBuilder() {
      return getField1();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (field1_ != null) {
        output.writeMessage(1, getField1());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (field1_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getField1());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.confluent.connect.protobuf.test.NestedKeyValue.NestedKeyValueMessage)) {
        return super.equals(obj);
      }
      io.confluent.connect.protobuf.test.NestedKeyValue.NestedKeyValueMessage other = (io.confluent.connect.protobuf.test.NestedKeyValue.NestedKeyValueMessage) obj;

      if (hasField1() != other.hasField1()) return false;
      if (hasField1()) {
        if (!getField1()
            .equals(other.getField1())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasField1()) {
        hash = (37 * hash) + FIELD1_FIELD_NUMBER;
        hash = (53 * hash) + getField1().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.confluent.connect.protobuf.test.NestedKeyValue.NestedKeyValueMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.confluent.connect.protobuf.test.NestedKeyValue.NestedKeyValueMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.confluent.connect.protobuf.test.NestedKeyValue.NestedKeyValueMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.confluent.connect.protobuf.test.NestedKeyValue.NestedKeyValueMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.confluent.connect.protobuf.test.NestedKeyValue.NestedKeyValueMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.confluent.connect.protobuf.test.NestedKeyValue.NestedKeyValueMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.confluent.connect.protobuf.test.NestedKeyValue.NestedKeyValueMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.confluent.connect.protobuf.test.NestedKeyValue.NestedKeyValueMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.confluent.connect.protobuf.test.NestedKeyValue.NestedKeyValueMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.confluent.connect.protobuf.test.NestedKeyValue.NestedKeyValueMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.confluent.connect.protobuf.test.NestedKeyValue.NestedKeyValueMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.confluent.connect.protobuf.test.NestedKeyValue.NestedKeyValueMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.confluent.connect.protobuf.test.NestedKeyValue.NestedKeyValueMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code NestedKeyValueMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:NestedKeyValueMessage)
        io.confluent.connect.protobuf.test.NestedKeyValue.NestedKeyValueMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.confluent.connect.protobuf.test.NestedKeyValue.internal_static_NestedKeyValueMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.confluent.connect.protobuf.test.NestedKeyValue.internal_static_NestedKeyValueMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.confluent.connect.protobuf.test.NestedKeyValue.NestedKeyValueMessage.class, io.confluent.connect.protobuf.test.NestedKeyValue.NestedKeyValueMessage.Builder.class);
      }

      // Construct using io.confluent.connect.protobuf.test.NestedKeyValue.NestedKeyValueMessage.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (field1Builder_ == null) {
          field1_ = null;
        } else {
          field1_ = null;
          field1Builder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.confluent.connect.protobuf.test.NestedKeyValue.internal_static_NestedKeyValueMessage_descriptor;
      }

      @java.lang.Override
      public io.confluent.connect.protobuf.test.NestedKeyValue.NestedKeyValueMessage getDefaultInstanceForType() {
        return io.confluent.connect.protobuf.test.NestedKeyValue.NestedKeyValueMessage.getDefaultInstance();
      }

      @java.lang.Override
      public io.confluent.connect.protobuf.test.NestedKeyValue.NestedKeyValueMessage build() {
        io.confluent.connect.protobuf.test.NestedKeyValue.NestedKeyValueMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.confluent.connect.protobuf.test.NestedKeyValue.NestedKeyValueMessage buildPartial() {
        io.confluent.connect.protobuf.test.NestedKeyValue.NestedKeyValueMessage result = new io.confluent.connect.protobuf.test.NestedKeyValue.NestedKeyValueMessage(this);
        if (field1Builder_ == null) {
          result.field1_ = field1_;
        } else {
          result.field1_ = field1Builder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.confluent.connect.protobuf.test.NestedKeyValue.NestedKeyValueMessage) {
          return mergeFrom((io.confluent.connect.protobuf.test.NestedKeyValue.NestedKeyValueMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.confluent.connect.protobuf.test.NestedKeyValue.NestedKeyValueMessage other) {
        if (other == io.confluent.connect.protobuf.test.NestedKeyValue.NestedKeyValueMessage.getDefaultInstance()) return this;
        if (other.hasField1()) {
          mergeField1(other.getField1());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getField1FieldBuilder().getBuilder(),
                    extensionRegistry);

                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private io.confluent.connect.protobuf.test.NestedKeyValue.AttributeFieldEntry field1_;
      private com.google.protobuf.SingleFieldBuilderV3<
          io.confluent.connect.protobuf.test.NestedKeyValue.AttributeFieldEntry, io.confluent.connect.protobuf.test.NestedKeyValue.AttributeFieldEntry.Builder, io.confluent.connect.protobuf.test.NestedKeyValue.AttributeFieldEntryOrBuilder> field1Builder_;
      /**
       * <code>.AttributeFieldEntry field1 = 1;</code>
       * @return Whether the field1 field is set.
       */
      public boolean hasField1() {
        return field1Builder_ != null || field1_ != null;
      }
      /**
       * <code>.AttributeFieldEntry field1 = 1;</code>
       * @return The field1.
       */
      public io.confluent.connect.protobuf.test.NestedKeyValue.AttributeFieldEntry getField1() {
        if (field1Builder_ == null) {
          return field1_ == null ? io.confluent.connect.protobuf.test.NestedKeyValue.AttributeFieldEntry.getDefaultInstance() : field1_;
        } else {
          return field1Builder_.getMessage();
        }
      }
      /**
       * <code>.AttributeFieldEntry field1 = 1;</code>
       */
      public Builder setField1(io.confluent.connect.protobuf.test.NestedKeyValue.AttributeFieldEntry value) {
        if (field1Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          field1_ = value;
          onChanged();
        } else {
          field1Builder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.AttributeFieldEntry field1 = 1;</code>
       */
      public Builder setField1(
          io.confluent.connect.protobuf.test.NestedKeyValue.AttributeFieldEntry.Builder builderForValue) {
        if (field1Builder_ == null) {
          field1_ = builderForValue.build();
          onChanged();
        } else {
          field1Builder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.AttributeFieldEntry field1 = 1;</code>
       */
      public Builder mergeField1(io.confluent.connect.protobuf.test.NestedKeyValue.AttributeFieldEntry value) {
        if (field1Builder_ == null) {
          if (field1_ != null) {
            field1_ =
              io.confluent.connect.protobuf.test.NestedKeyValue.AttributeFieldEntry.newBuilder(field1_).mergeFrom(value).buildPartial();
          } else {
            field1_ = value;
          }
          onChanged();
        } else {
          field1Builder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.AttributeFieldEntry field1 = 1;</code>
       */
      public Builder clearField1() {
        if (field1Builder_ == null) {
          field1_ = null;
          onChanged();
        } else {
          field1_ = null;
          field1Builder_ = null;
        }

        return this;
      }
      /**
       * <code>.AttributeFieldEntry field1 = 1;</code>
       */
      public io.confluent.connect.protobuf.test.NestedKeyValue.AttributeFieldEntry.Builder getField1Builder() {
        
        onChanged();
        return getField1FieldBuilder().getBuilder();
      }
      /**
       * <code>.AttributeFieldEntry field1 = 1;</code>
       */
      public io.confluent.connect.protobuf.test.NestedKeyValue.AttributeFieldEntryOrBuilder getField1OrBuilder() {
        if (field1Builder_ != null) {
          return field1Builder_.getMessageOrBuilder();
        } else {
          return field1_ == null ?
              io.confluent.connect.protobuf.test.NestedKeyValue.AttributeFieldEntry.getDefaultInstance() : field1_;
        }
      }
      /**
       * <code>.AttributeFieldEntry field1 = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          io.confluent.connect.protobuf.test.NestedKeyValue.AttributeFieldEntry, io.confluent.connect.protobuf.test.NestedKeyValue.AttributeFieldEntry.Builder, io.confluent.connect.protobuf.test.NestedKeyValue.AttributeFieldEntryOrBuilder> 
          getField1FieldBuilder() {
        if (field1Builder_ == null) {
          field1Builder_ = new com.google.protobuf.SingleFieldBuilderV3<
              io.confluent.connect.protobuf.test.NestedKeyValue.AttributeFieldEntry, io.confluent.connect.protobuf.test.NestedKeyValue.AttributeFieldEntry.Builder, io.confluent.connect.protobuf.test.NestedKeyValue.AttributeFieldEntryOrBuilder>(
                  getField1(),
                  getParentForChildren(),
                  isClean());
          field1_ = null;
        }
        return field1Builder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:NestedKeyValueMessage)
    }

    // @@protoc_insertion_point(class_scope:NestedKeyValueMessage)
    private static final io.confluent.connect.protobuf.test.NestedKeyValue.NestedKeyValueMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.confluent.connect.protobuf.test.NestedKeyValue.NestedKeyValueMessage();
    }

    public static io.confluent.connect.protobuf.test.NestedKeyValue.NestedKeyValueMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NestedKeyValueMessage>
        PARSER = new com.google.protobuf.AbstractParser<NestedKeyValueMessage>() {
      @java.lang.Override
      public NestedKeyValueMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<NestedKeyValueMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NestedKeyValueMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.confluent.connect.protobuf.test.NestedKeyValue.NestedKeyValueMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AttributeFieldEntryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AttributeFieldEntry)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 i32 = 1;</code>
     * @return The i32.
     */
    int getI32();

    /**
     * <code>double d = 2;</code>
     * @return The d.
     */
    double getD();
  }
  /**
   * Protobuf type {@code AttributeFieldEntry}
   */
  public static final class AttributeFieldEntry extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:AttributeFieldEntry)
      AttributeFieldEntryOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AttributeFieldEntry.newBuilder() to construct.
    private AttributeFieldEntry(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AttributeFieldEntry() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AttributeFieldEntry();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.confluent.connect.protobuf.test.NestedKeyValue.internal_static_AttributeFieldEntry_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.confluent.connect.protobuf.test.NestedKeyValue.internal_static_AttributeFieldEntry_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.confluent.connect.protobuf.test.NestedKeyValue.AttributeFieldEntry.class, io.confluent.connect.protobuf.test.NestedKeyValue.AttributeFieldEntry.Builder.class);
    }

    public static final int I32_FIELD_NUMBER = 1;
    private int i32_;
    /**
     * <code>int32 i32 = 1;</code>
     * @return The i32.
     */
    @java.lang.Override
    public int getI32() {
      return i32_;
    }

    public static final int D_FIELD_NUMBER = 2;
    private double d_;
    /**
     * <code>double d = 2;</code>
     * @return The d.
     */
    @java.lang.Override
    public double getD() {
      return d_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (i32_ != 0) {
        output.writeInt32(1, i32_);
      }
      if (java.lang.Double.doubleToRawLongBits(d_) != 0) {
        output.writeDouble(2, d_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (i32_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, i32_);
      }
      if (java.lang.Double.doubleToRawLongBits(d_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, d_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.confluent.connect.protobuf.test.NestedKeyValue.AttributeFieldEntry)) {
        return super.equals(obj);
      }
      io.confluent.connect.protobuf.test.NestedKeyValue.AttributeFieldEntry other = (io.confluent.connect.protobuf.test.NestedKeyValue.AttributeFieldEntry) obj;

      if (getI32()
          != other.getI32()) return false;
      if (java.lang.Double.doubleToLongBits(getD())
          != java.lang.Double.doubleToLongBits(
              other.getD())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + I32_FIELD_NUMBER;
      hash = (53 * hash) + getI32();
      hash = (37 * hash) + D_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getD()));
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.confluent.connect.protobuf.test.NestedKeyValue.AttributeFieldEntry parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.confluent.connect.protobuf.test.NestedKeyValue.AttributeFieldEntry parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.confluent.connect.protobuf.test.NestedKeyValue.AttributeFieldEntry parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.confluent.connect.protobuf.test.NestedKeyValue.AttributeFieldEntry parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.confluent.connect.protobuf.test.NestedKeyValue.AttributeFieldEntry parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.confluent.connect.protobuf.test.NestedKeyValue.AttributeFieldEntry parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.confluent.connect.protobuf.test.NestedKeyValue.AttributeFieldEntry parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.confluent.connect.protobuf.test.NestedKeyValue.AttributeFieldEntry parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.confluent.connect.protobuf.test.NestedKeyValue.AttributeFieldEntry parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.confluent.connect.protobuf.test.NestedKeyValue.AttributeFieldEntry parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.confluent.connect.protobuf.test.NestedKeyValue.AttributeFieldEntry parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.confluent.connect.protobuf.test.NestedKeyValue.AttributeFieldEntry parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.confluent.connect.protobuf.test.NestedKeyValue.AttributeFieldEntry prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AttributeFieldEntry}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AttributeFieldEntry)
        io.confluent.connect.protobuf.test.NestedKeyValue.AttributeFieldEntryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.confluent.connect.protobuf.test.NestedKeyValue.internal_static_AttributeFieldEntry_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.confluent.connect.protobuf.test.NestedKeyValue.internal_static_AttributeFieldEntry_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.confluent.connect.protobuf.test.NestedKeyValue.AttributeFieldEntry.class, io.confluent.connect.protobuf.test.NestedKeyValue.AttributeFieldEntry.Builder.class);
      }

      // Construct using io.confluent.connect.protobuf.test.NestedKeyValue.AttributeFieldEntry.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        i32_ = 0;

        d_ = 0D;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.confluent.connect.protobuf.test.NestedKeyValue.internal_static_AttributeFieldEntry_descriptor;
      }

      @java.lang.Override
      public io.confluent.connect.protobuf.test.NestedKeyValue.AttributeFieldEntry getDefaultInstanceForType() {
        return io.confluent.connect.protobuf.test.NestedKeyValue.AttributeFieldEntry.getDefaultInstance();
      }

      @java.lang.Override
      public io.confluent.connect.protobuf.test.NestedKeyValue.AttributeFieldEntry build() {
        io.confluent.connect.protobuf.test.NestedKeyValue.AttributeFieldEntry result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.confluent.connect.protobuf.test.NestedKeyValue.AttributeFieldEntry buildPartial() {
        io.confluent.connect.protobuf.test.NestedKeyValue.AttributeFieldEntry result = new io.confluent.connect.protobuf.test.NestedKeyValue.AttributeFieldEntry(this);
        result.i32_ = i32_;
        result.d_ = d_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.confluent.connect.protobuf.test.NestedKeyValue.AttributeFieldEntry) {
          return mergeFrom((io.confluent.connect.protobuf.test.NestedKeyValue.AttributeFieldEntry)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.confluent.connect.protobuf.test.NestedKeyValue.AttributeFieldEntry other) {
        if (other == io.confluent.connect.protobuf.test.NestedKeyValue.AttributeFieldEntry.getDefaultInstance()) return this;
        if (other.getI32() != 0) {
          setI32(other.getI32());
        }
        if (other.getD() != 0D) {
          setD(other.getD());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                i32_ = input.readInt32();

                break;
              } // case 8
              case 17: {
                d_ = input.readDouble();

                break;
              } // case 17
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private int i32_ ;
      /**
       * <code>int32 i32 = 1;</code>
       * @return The i32.
       */
      @java.lang.Override
      public int getI32() {
        return i32_;
      }
      /**
       * <code>int32 i32 = 1;</code>
       * @param value The i32 to set.
       * @return This builder for chaining.
       */
      public Builder setI32(int value) {
        
        i32_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 i32 = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearI32() {
        
        i32_ = 0;
        onChanged();
        return this;
      }

      private double d_ ;
      /**
       * <code>double d = 2;</code>
       * @return The d.
       */
      @java.lang.Override
      public double getD() {
        return d_;
      }
      /**
       * <code>double d = 2;</code>
       * @param value The d to set.
       * @return This builder for chaining.
       */
      public Builder setD(double value) {
        
        d_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double d = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearD() {
        
        d_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:AttributeFieldEntry)
    }

    // @@protoc_insertion_point(class_scope:AttributeFieldEntry)
    private static final io.confluent.connect.protobuf.test.NestedKeyValue.AttributeFieldEntry DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.confluent.connect.protobuf.test.NestedKeyValue.AttributeFieldEntry();
    }

    public static io.confluent.connect.protobuf.test.NestedKeyValue.AttributeFieldEntry getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AttributeFieldEntry>
        PARSER = new com.google.protobuf.AbstractParser<AttributeFieldEntry>() {
      @java.lang.Override
      public AttributeFieldEntry parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<AttributeFieldEntry> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AttributeFieldEntry> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.confluent.connect.protobuf.test.NestedKeyValue.AttributeFieldEntry getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NestedKeyValueMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NestedKeyValueMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AttributeFieldEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AttributeFieldEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021nestedfield.proto\032 google/protobuf/des" +
      "criptor.proto\"=\n\025NestedKeyValueMessage\022$" +
      "\n\006field1\030\001 \001(\0132\024.AttributeFieldEntry\"-\n\023" +
      "AttributeFieldEntry\022\013\n\003i32\030\001 \001(\005\022\t\n\001d\030\002 " +
      "\001(\001B4\n\"io.confluent.connect.protobuf.tes" +
      "tB\016NestedKeyValueb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        });
    internal_static_NestedKeyValueMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_NestedKeyValueMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NestedKeyValueMessage_descriptor,
        new java.lang.String[] { "Field1", });
    internal_static_AttributeFieldEntry_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_AttributeFieldEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AttributeFieldEntry_descriptor,
        new java.lang.String[] { "I32", "D", });
    com.google.protobuf.DescriptorProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
