// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: nestedfield.proto
// Protobuf Java Version: 4.29.3

package io.confluent.connect.protobuf.test;

public final class NestedKeyValue {
  private NestedKeyValue() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      NestedKeyValue.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface NestedKeyValueMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:NestedKeyValueMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.NestedAttributeFieldEntry wrapper_field = 1;</code>
     * @return Whether the wrapperField field is set.
     */
    boolean hasWrapperField();
    /**
     * <code>.NestedAttributeFieldEntry wrapper_field = 1;</code>
     * @return The wrapperField.
     */
    io.confluent.connect.protobuf.test.NestedKeyValue.NestedAttributeFieldEntry getWrapperField();
    /**
     * <code>.NestedAttributeFieldEntry wrapper_field = 1;</code>
     */
    io.confluent.connect.protobuf.test.NestedKeyValue.NestedAttributeFieldEntryOrBuilder getWrapperFieldOrBuilder();

    /**
     * <code>double inner_field = 2;</code>
     * @return The innerField.
     */
    double getInnerField();
  }
  /**
   * Protobuf type {@code NestedKeyValueMessage}
   */
  public static final class NestedKeyValueMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:NestedKeyValueMessage)
      NestedKeyValueMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        NestedKeyValueMessage.class.getName());
    }
    // Use NestedKeyValueMessage.newBuilder() to construct.
    private NestedKeyValueMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private NestedKeyValueMessage() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.confluent.connect.protobuf.test.NestedKeyValue.internal_static_NestedKeyValueMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.confluent.connect.protobuf.test.NestedKeyValue.internal_static_NestedKeyValueMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.confluent.connect.protobuf.test.NestedKeyValue.NestedKeyValueMessage.class, io.confluent.connect.protobuf.test.NestedKeyValue.NestedKeyValueMessage.Builder.class);
    }

    private int bitField0_;
    public static final int WRAPPER_FIELD_FIELD_NUMBER = 1;
    private io.confluent.connect.protobuf.test.NestedKeyValue.NestedAttributeFieldEntry wrapperField_;
    /**
     * <code>.NestedAttributeFieldEntry wrapper_field = 1;</code>
     * @return Whether the wrapperField field is set.
     */
    @java.lang.Override
    public boolean hasWrapperField() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.NestedAttributeFieldEntry wrapper_field = 1;</code>
     * @return The wrapperField.
     */
    @java.lang.Override
    public io.confluent.connect.protobuf.test.NestedKeyValue.NestedAttributeFieldEntry getWrapperField() {
      return wrapperField_ == null ? io.confluent.connect.protobuf.test.NestedKeyValue.NestedAttributeFieldEntry.getDefaultInstance() : wrapperField_;
    }
    /**
     * <code>.NestedAttributeFieldEntry wrapper_field = 1;</code>
     */
    @java.lang.Override
    public io.confluent.connect.protobuf.test.NestedKeyValue.NestedAttributeFieldEntryOrBuilder getWrapperFieldOrBuilder() {
      return wrapperField_ == null ? io.confluent.connect.protobuf.test.NestedKeyValue.NestedAttributeFieldEntry.getDefaultInstance() : wrapperField_;
    }

    public static final int INNER_FIELD_FIELD_NUMBER = 2;
    private double innerField_ = 0D;
    /**
     * <code>double inner_field = 2;</code>
     * @return The innerField.
     */
    @java.lang.Override
    public double getInnerField() {
      return innerField_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getWrapperField());
      }
      if (java.lang.Double.doubleToRawLongBits(innerField_) != 0) {
        output.writeDouble(2, innerField_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getWrapperField());
      }
      if (java.lang.Double.doubleToRawLongBits(innerField_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, innerField_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.confluent.connect.protobuf.test.NestedKeyValue.NestedKeyValueMessage)) {
        return super.equals(obj);
      }
      io.confluent.connect.protobuf.test.NestedKeyValue.NestedKeyValueMessage other = (io.confluent.connect.protobuf.test.NestedKeyValue.NestedKeyValueMessage) obj;

      if (hasWrapperField() != other.hasWrapperField()) return false;
      if (hasWrapperField()) {
        if (!getWrapperField()
            .equals(other.getWrapperField())) return false;
      }
      if (java.lang.Double.doubleToLongBits(getInnerField())
          != java.lang.Double.doubleToLongBits(
              other.getInnerField())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasWrapperField()) {
        hash = (37 * hash) + WRAPPER_FIELD_FIELD_NUMBER;
        hash = (53 * hash) + getWrapperField().hashCode();
      }
      hash = (37 * hash) + INNER_FIELD_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getInnerField()));
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.confluent.connect.protobuf.test.NestedKeyValue.NestedKeyValueMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.confluent.connect.protobuf.test.NestedKeyValue.NestedKeyValueMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.confluent.connect.protobuf.test.NestedKeyValue.NestedKeyValueMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.confluent.connect.protobuf.test.NestedKeyValue.NestedKeyValueMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.confluent.connect.protobuf.test.NestedKeyValue.NestedKeyValueMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.confluent.connect.protobuf.test.NestedKeyValue.NestedKeyValueMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.confluent.connect.protobuf.test.NestedKeyValue.NestedKeyValueMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static io.confluent.connect.protobuf.test.NestedKeyValue.NestedKeyValueMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static io.confluent.connect.protobuf.test.NestedKeyValue.NestedKeyValueMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static io.confluent.connect.protobuf.test.NestedKeyValue.NestedKeyValueMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.confluent.connect.protobuf.test.NestedKeyValue.NestedKeyValueMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static io.confluent.connect.protobuf.test.NestedKeyValue.NestedKeyValueMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.confluent.connect.protobuf.test.NestedKeyValue.NestedKeyValueMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code NestedKeyValueMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:NestedKeyValueMessage)
        io.confluent.connect.protobuf.test.NestedKeyValue.NestedKeyValueMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.confluent.connect.protobuf.test.NestedKeyValue.internal_static_NestedKeyValueMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.confluent.connect.protobuf.test.NestedKeyValue.internal_static_NestedKeyValueMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.confluent.connect.protobuf.test.NestedKeyValue.NestedKeyValueMessage.class, io.confluent.connect.protobuf.test.NestedKeyValue.NestedKeyValueMessage.Builder.class);
      }

      // Construct using io.confluent.connect.protobuf.test.NestedKeyValue.NestedKeyValueMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          getWrapperFieldFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        wrapperField_ = null;
        if (wrapperFieldBuilder_ != null) {
          wrapperFieldBuilder_.dispose();
          wrapperFieldBuilder_ = null;
        }
        innerField_ = 0D;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.confluent.connect.protobuf.test.NestedKeyValue.internal_static_NestedKeyValueMessage_descriptor;
      }

      @java.lang.Override
      public io.confluent.connect.protobuf.test.NestedKeyValue.NestedKeyValueMessage getDefaultInstanceForType() {
        return io.confluent.connect.protobuf.test.NestedKeyValue.NestedKeyValueMessage.getDefaultInstance();
      }

      @java.lang.Override
      public io.confluent.connect.protobuf.test.NestedKeyValue.NestedKeyValueMessage build() {
        io.confluent.connect.protobuf.test.NestedKeyValue.NestedKeyValueMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.confluent.connect.protobuf.test.NestedKeyValue.NestedKeyValueMessage buildPartial() {
        io.confluent.connect.protobuf.test.NestedKeyValue.NestedKeyValueMessage result = new io.confluent.connect.protobuf.test.NestedKeyValue.NestedKeyValueMessage(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(io.confluent.connect.protobuf.test.NestedKeyValue.NestedKeyValueMessage result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.wrapperField_ = wrapperFieldBuilder_ == null
              ? wrapperField_
              : wrapperFieldBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.innerField_ = innerField_;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.confluent.connect.protobuf.test.NestedKeyValue.NestedKeyValueMessage) {
          return mergeFrom((io.confluent.connect.protobuf.test.NestedKeyValue.NestedKeyValueMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.confluent.connect.protobuf.test.NestedKeyValue.NestedKeyValueMessage other) {
        if (other == io.confluent.connect.protobuf.test.NestedKeyValue.NestedKeyValueMessage.getDefaultInstance()) return this;
        if (other.hasWrapperField()) {
          mergeWrapperField(other.getWrapperField());
        }
        if (other.getInnerField() != 0D) {
          setInnerField(other.getInnerField());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getWrapperFieldFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 17: {
                innerField_ = input.readDouble();
                bitField0_ |= 0x00000002;
                break;
              } // case 17
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private io.confluent.connect.protobuf.test.NestedKeyValue.NestedAttributeFieldEntry wrapperField_;
      private com.google.protobuf.SingleFieldBuilder<
          io.confluent.connect.protobuf.test.NestedKeyValue.NestedAttributeFieldEntry, io.confluent.connect.protobuf.test.NestedKeyValue.NestedAttributeFieldEntry.Builder, io.confluent.connect.protobuf.test.NestedKeyValue.NestedAttributeFieldEntryOrBuilder> wrapperFieldBuilder_;
      /**
       * <code>.NestedAttributeFieldEntry wrapper_field = 1;</code>
       * @return Whether the wrapperField field is set.
       */
      public boolean hasWrapperField() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.NestedAttributeFieldEntry wrapper_field = 1;</code>
       * @return The wrapperField.
       */
      public io.confluent.connect.protobuf.test.NestedKeyValue.NestedAttributeFieldEntry getWrapperField() {
        if (wrapperFieldBuilder_ == null) {
          return wrapperField_ == null ? io.confluent.connect.protobuf.test.NestedKeyValue.NestedAttributeFieldEntry.getDefaultInstance() : wrapperField_;
        } else {
          return wrapperFieldBuilder_.getMessage();
        }
      }
      /**
       * <code>.NestedAttributeFieldEntry wrapper_field = 1;</code>
       */
      public Builder setWrapperField(io.confluent.connect.protobuf.test.NestedKeyValue.NestedAttributeFieldEntry value) {
        if (wrapperFieldBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          wrapperField_ = value;
        } else {
          wrapperFieldBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.NestedAttributeFieldEntry wrapper_field = 1;</code>
       */
      public Builder setWrapperField(
          io.confluent.connect.protobuf.test.NestedKeyValue.NestedAttributeFieldEntry.Builder builderForValue) {
        if (wrapperFieldBuilder_ == null) {
          wrapperField_ = builderForValue.build();
        } else {
          wrapperFieldBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.NestedAttributeFieldEntry wrapper_field = 1;</code>
       */
      public Builder mergeWrapperField(io.confluent.connect.protobuf.test.NestedKeyValue.NestedAttributeFieldEntry value) {
        if (wrapperFieldBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            wrapperField_ != null &&
            wrapperField_ != io.confluent.connect.protobuf.test.NestedKeyValue.NestedAttributeFieldEntry.getDefaultInstance()) {
            getWrapperFieldBuilder().mergeFrom(value);
          } else {
            wrapperField_ = value;
          }
        } else {
          wrapperFieldBuilder_.mergeFrom(value);
        }
        if (wrapperField_ != null) {
          bitField0_ |= 0x00000001;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.NestedAttributeFieldEntry wrapper_field = 1;</code>
       */
      public Builder clearWrapperField() {
        bitField0_ = (bitField0_ & ~0x00000001);
        wrapperField_ = null;
        if (wrapperFieldBuilder_ != null) {
          wrapperFieldBuilder_.dispose();
          wrapperFieldBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.NestedAttributeFieldEntry wrapper_field = 1;</code>
       */
      public io.confluent.connect.protobuf.test.NestedKeyValue.NestedAttributeFieldEntry.Builder getWrapperFieldBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getWrapperFieldFieldBuilder().getBuilder();
      }
      /**
       * <code>.NestedAttributeFieldEntry wrapper_field = 1;</code>
       */
      public io.confluent.connect.protobuf.test.NestedKeyValue.NestedAttributeFieldEntryOrBuilder getWrapperFieldOrBuilder() {
        if (wrapperFieldBuilder_ != null) {
          return wrapperFieldBuilder_.getMessageOrBuilder();
        } else {
          return wrapperField_ == null ?
              io.confluent.connect.protobuf.test.NestedKeyValue.NestedAttributeFieldEntry.getDefaultInstance() : wrapperField_;
        }
      }
      /**
       * <code>.NestedAttributeFieldEntry wrapper_field = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          io.confluent.connect.protobuf.test.NestedKeyValue.NestedAttributeFieldEntry, io.confluent.connect.protobuf.test.NestedKeyValue.NestedAttributeFieldEntry.Builder, io.confluent.connect.protobuf.test.NestedKeyValue.NestedAttributeFieldEntryOrBuilder> 
          getWrapperFieldFieldBuilder() {
        if (wrapperFieldBuilder_ == null) {
          wrapperFieldBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              io.confluent.connect.protobuf.test.NestedKeyValue.NestedAttributeFieldEntry, io.confluent.connect.protobuf.test.NestedKeyValue.NestedAttributeFieldEntry.Builder, io.confluent.connect.protobuf.test.NestedKeyValue.NestedAttributeFieldEntryOrBuilder>(
                  getWrapperField(),
                  getParentForChildren(),
                  isClean());
          wrapperField_ = null;
        }
        return wrapperFieldBuilder_;
      }

      private double innerField_ ;
      /**
       * <code>double inner_field = 2;</code>
       * @return The innerField.
       */
      @java.lang.Override
      public double getInnerField() {
        return innerField_;
      }
      /**
       * <code>double inner_field = 2;</code>
       * @param value The innerField to set.
       * @return This builder for chaining.
       */
      public Builder setInnerField(double value) {

        innerField_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>double inner_field = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearInnerField() {
        bitField0_ = (bitField0_ & ~0x00000002);
        innerField_ = 0D;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:NestedKeyValueMessage)
    }

    // @@protoc_insertion_point(class_scope:NestedKeyValueMessage)
    private static final io.confluent.connect.protobuf.test.NestedKeyValue.NestedKeyValueMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.confluent.connect.protobuf.test.NestedKeyValue.NestedKeyValueMessage();
    }

    public static io.confluent.connect.protobuf.test.NestedKeyValue.NestedKeyValueMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NestedKeyValueMessage>
        PARSER = new com.google.protobuf.AbstractParser<NestedKeyValueMessage>() {
      @java.lang.Override
      public NestedKeyValueMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<NestedKeyValueMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NestedKeyValueMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.confluent.connect.protobuf.test.NestedKeyValue.NestedKeyValueMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface NestedAttributeFieldEntryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:NestedAttributeFieldEntry)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>double nested_field = 1;</code>
     * @return The nestedField.
     */
    double getNestedField();
  }
  /**
   * Protobuf type {@code NestedAttributeFieldEntry}
   */
  public static final class NestedAttributeFieldEntry extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:NestedAttributeFieldEntry)
      NestedAttributeFieldEntryOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        NestedAttributeFieldEntry.class.getName());
    }
    // Use NestedAttributeFieldEntry.newBuilder() to construct.
    private NestedAttributeFieldEntry(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private NestedAttributeFieldEntry() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.confluent.connect.protobuf.test.NestedKeyValue.internal_static_NestedAttributeFieldEntry_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.confluent.connect.protobuf.test.NestedKeyValue.internal_static_NestedAttributeFieldEntry_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.confluent.connect.protobuf.test.NestedKeyValue.NestedAttributeFieldEntry.class, io.confluent.connect.protobuf.test.NestedKeyValue.NestedAttributeFieldEntry.Builder.class);
    }

    public static final int NESTED_FIELD_FIELD_NUMBER = 1;
    private double nestedField_ = 0D;
    /**
     * <code>double nested_field = 1;</code>
     * @return The nestedField.
     */
    @java.lang.Override
    public double getNestedField() {
      return nestedField_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (java.lang.Double.doubleToRawLongBits(nestedField_) != 0) {
        output.writeDouble(1, nestedField_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (java.lang.Double.doubleToRawLongBits(nestedField_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, nestedField_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.confluent.connect.protobuf.test.NestedKeyValue.NestedAttributeFieldEntry)) {
        return super.equals(obj);
      }
      io.confluent.connect.protobuf.test.NestedKeyValue.NestedAttributeFieldEntry other = (io.confluent.connect.protobuf.test.NestedKeyValue.NestedAttributeFieldEntry) obj;

      if (java.lang.Double.doubleToLongBits(getNestedField())
          != java.lang.Double.doubleToLongBits(
              other.getNestedField())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NESTED_FIELD_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getNestedField()));
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.confluent.connect.protobuf.test.NestedKeyValue.NestedAttributeFieldEntry parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.confluent.connect.protobuf.test.NestedKeyValue.NestedAttributeFieldEntry parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.confluent.connect.protobuf.test.NestedKeyValue.NestedAttributeFieldEntry parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.confluent.connect.protobuf.test.NestedKeyValue.NestedAttributeFieldEntry parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.confluent.connect.protobuf.test.NestedKeyValue.NestedAttributeFieldEntry parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.confluent.connect.protobuf.test.NestedKeyValue.NestedAttributeFieldEntry parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.confluent.connect.protobuf.test.NestedKeyValue.NestedAttributeFieldEntry parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static io.confluent.connect.protobuf.test.NestedKeyValue.NestedAttributeFieldEntry parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static io.confluent.connect.protobuf.test.NestedKeyValue.NestedAttributeFieldEntry parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static io.confluent.connect.protobuf.test.NestedKeyValue.NestedAttributeFieldEntry parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.confluent.connect.protobuf.test.NestedKeyValue.NestedAttributeFieldEntry parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static io.confluent.connect.protobuf.test.NestedKeyValue.NestedAttributeFieldEntry parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.confluent.connect.protobuf.test.NestedKeyValue.NestedAttributeFieldEntry prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code NestedAttributeFieldEntry}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:NestedAttributeFieldEntry)
        io.confluent.connect.protobuf.test.NestedKeyValue.NestedAttributeFieldEntryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.confluent.connect.protobuf.test.NestedKeyValue.internal_static_NestedAttributeFieldEntry_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.confluent.connect.protobuf.test.NestedKeyValue.internal_static_NestedAttributeFieldEntry_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.confluent.connect.protobuf.test.NestedKeyValue.NestedAttributeFieldEntry.class, io.confluent.connect.protobuf.test.NestedKeyValue.NestedAttributeFieldEntry.Builder.class);
      }

      // Construct using io.confluent.connect.protobuf.test.NestedKeyValue.NestedAttributeFieldEntry.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        nestedField_ = 0D;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.confluent.connect.protobuf.test.NestedKeyValue.internal_static_NestedAttributeFieldEntry_descriptor;
      }

      @java.lang.Override
      public io.confluent.connect.protobuf.test.NestedKeyValue.NestedAttributeFieldEntry getDefaultInstanceForType() {
        return io.confluent.connect.protobuf.test.NestedKeyValue.NestedAttributeFieldEntry.getDefaultInstance();
      }

      @java.lang.Override
      public io.confluent.connect.protobuf.test.NestedKeyValue.NestedAttributeFieldEntry build() {
        io.confluent.connect.protobuf.test.NestedKeyValue.NestedAttributeFieldEntry result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.confluent.connect.protobuf.test.NestedKeyValue.NestedAttributeFieldEntry buildPartial() {
        io.confluent.connect.protobuf.test.NestedKeyValue.NestedAttributeFieldEntry result = new io.confluent.connect.protobuf.test.NestedKeyValue.NestedAttributeFieldEntry(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(io.confluent.connect.protobuf.test.NestedKeyValue.NestedAttributeFieldEntry result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.nestedField_ = nestedField_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.confluent.connect.protobuf.test.NestedKeyValue.NestedAttributeFieldEntry) {
          return mergeFrom((io.confluent.connect.protobuf.test.NestedKeyValue.NestedAttributeFieldEntry)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.confluent.connect.protobuf.test.NestedKeyValue.NestedAttributeFieldEntry other) {
        if (other == io.confluent.connect.protobuf.test.NestedKeyValue.NestedAttributeFieldEntry.getDefaultInstance()) return this;
        if (other.getNestedField() != 0D) {
          setNestedField(other.getNestedField());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 9: {
                nestedField_ = input.readDouble();
                bitField0_ |= 0x00000001;
                break;
              } // case 9
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private double nestedField_ ;
      /**
       * <code>double nested_field = 1;</code>
       * @return The nestedField.
       */
      @java.lang.Override
      public double getNestedField() {
        return nestedField_;
      }
      /**
       * <code>double nested_field = 1;</code>
       * @param value The nestedField to set.
       * @return This builder for chaining.
       */
      public Builder setNestedField(double value) {

        nestedField_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>double nested_field = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearNestedField() {
        bitField0_ = (bitField0_ & ~0x00000001);
        nestedField_ = 0D;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:NestedAttributeFieldEntry)
    }

    // @@protoc_insertion_point(class_scope:NestedAttributeFieldEntry)
    private static final io.confluent.connect.protobuf.test.NestedKeyValue.NestedAttributeFieldEntry DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.confluent.connect.protobuf.test.NestedKeyValue.NestedAttributeFieldEntry();
    }

    public static io.confluent.connect.protobuf.test.NestedKeyValue.NestedAttributeFieldEntry getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NestedAttributeFieldEntry>
        PARSER = new com.google.protobuf.AbstractParser<NestedAttributeFieldEntry>() {
      @java.lang.Override
      public NestedAttributeFieldEntry parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<NestedAttributeFieldEntry> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NestedAttributeFieldEntry> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.confluent.connect.protobuf.test.NestedKeyValue.NestedAttributeFieldEntry getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NestedKeyValueMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_NestedKeyValueMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NestedAttributeFieldEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_NestedAttributeFieldEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021nestedfield.proto\032 google/protobuf/des" +
      "criptor.proto\"_\n\025NestedKeyValueMessage\0221" +
      "\n\rwrapper_field\030\001 \001(\0132\032.NestedAttributeF" +
      "ieldEntry\022\023\n\013inner_field\030\002 \001(\001\"1\n\031Nested" +
      "AttributeFieldEntry\022\024\n\014nested_field\030\001 \001(" +
      "\001B4\n\"io.confluent.connect.protobuf.testB" +
      "\016NestedKeyValueb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        });
    internal_static_NestedKeyValueMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_NestedKeyValueMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_NestedKeyValueMessage_descriptor,
        new java.lang.String[] { "WrapperField", "InnerField", });
    internal_static_NestedAttributeFieldEntry_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_NestedAttributeFieldEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_NestedAttributeFieldEntry_descriptor,
        new java.lang.String[] { "NestedField", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.DescriptorProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
