repos:
  - repo: local
    hooks:
      - id: spotless
        name: spotless
        entry: mvn
        args: ['spotless:apply', '-DspotlessSetLicenseHeaderYearsFromGitHistory=true']
        language: system
        types: [java]