// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Pii.proto

package io.confluent.kafka.schemaregistry.rules;

public final class PiiProto {
  private PiiProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PiiOrBuilder extends
      // @@protoc_insertion_point(interface_extends:io.confluent.kafka.schemaregistry.rules.Pii)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string pii = 1 [(.confluent.field_meta) = { ... }</code>
     * @return The pii.
     */
    java.lang.String getPii();
    /**
     * <code>string pii = 1 [(.confluent.field_meta) = { ... }</code>
     * @return The bytes for pii.
     */
    com.google.protobuf.ByteString
        getPiiBytes();
  }
  /**
   * Protobuf type {@code io.confluent.kafka.schemaregistry.rules.Pii}
   */
  public static final class Pii extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:io.confluent.kafka.schemaregistry.rules.Pii)
      PiiOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Pii.newBuilder() to construct.
    private Pii(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Pii() {
      pii_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Pii();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.confluent.kafka.schemaregistry.rules.PiiProto.internal_static_io_confluent_kafka_schemaregistry_rules_Pii_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.confluent.kafka.schemaregistry.rules.PiiProto.internal_static_io_confluent_kafka_schemaregistry_rules_Pii_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.confluent.kafka.schemaregistry.rules.PiiProto.Pii.class, io.confluent.kafka.schemaregistry.rules.PiiProto.Pii.Builder.class);
    }

    public static final int PII_FIELD_NUMBER = 1;
    private volatile java.lang.Object pii_;
    /**
     * <code>string pii = 1 [(.confluent.field_meta) = { ... }</code>
     * @return The pii.
     */
    @java.lang.Override
    public java.lang.String getPii() {
      java.lang.Object ref = pii_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pii_ = s;
        return s;
      }
    }
    /**
     * <code>string pii = 1 [(.confluent.field_meta) = { ... }</code>
     * @return The bytes for pii.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPiiBytes() {
      java.lang.Object ref = pii_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pii_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(pii_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, pii_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(pii_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, pii_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.confluent.kafka.schemaregistry.rules.PiiProto.Pii)) {
        return super.equals(obj);
      }
      io.confluent.kafka.schemaregistry.rules.PiiProto.Pii other = (io.confluent.kafka.schemaregistry.rules.PiiProto.Pii) obj;

      if (!getPii()
          .equals(other.getPii())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PII_FIELD_NUMBER;
      hash = (53 * hash) + getPii().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.confluent.kafka.schemaregistry.rules.PiiProto.Pii parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.confluent.kafka.schemaregistry.rules.PiiProto.Pii parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.confluent.kafka.schemaregistry.rules.PiiProto.Pii parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.confluent.kafka.schemaregistry.rules.PiiProto.Pii parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.confluent.kafka.schemaregistry.rules.PiiProto.Pii parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.confluent.kafka.schemaregistry.rules.PiiProto.Pii parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.confluent.kafka.schemaregistry.rules.PiiProto.Pii parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.confluent.kafka.schemaregistry.rules.PiiProto.Pii parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.confluent.kafka.schemaregistry.rules.PiiProto.Pii parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.confluent.kafka.schemaregistry.rules.PiiProto.Pii parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.confluent.kafka.schemaregistry.rules.PiiProto.Pii parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.confluent.kafka.schemaregistry.rules.PiiProto.Pii parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.confluent.kafka.schemaregistry.rules.PiiProto.Pii prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code io.confluent.kafka.schemaregistry.rules.Pii}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:io.confluent.kafka.schemaregistry.rules.Pii)
        io.confluent.kafka.schemaregistry.rules.PiiProto.PiiOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.confluent.kafka.schemaregistry.rules.PiiProto.internal_static_io_confluent_kafka_schemaregistry_rules_Pii_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.confluent.kafka.schemaregistry.rules.PiiProto.internal_static_io_confluent_kafka_schemaregistry_rules_Pii_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.confluent.kafka.schemaregistry.rules.PiiProto.Pii.class, io.confluent.kafka.schemaregistry.rules.PiiProto.Pii.Builder.class);
      }

      // Construct using io.confluent.kafka.schemaregistry.rules.PiiProto.Pii.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        pii_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.confluent.kafka.schemaregistry.rules.PiiProto.internal_static_io_confluent_kafka_schemaregistry_rules_Pii_descriptor;
      }

      @java.lang.Override
      public io.confluent.kafka.schemaregistry.rules.PiiProto.Pii getDefaultInstanceForType() {
        return io.confluent.kafka.schemaregistry.rules.PiiProto.Pii.getDefaultInstance();
      }

      @java.lang.Override
      public io.confluent.kafka.schemaregistry.rules.PiiProto.Pii build() {
        io.confluent.kafka.schemaregistry.rules.PiiProto.Pii result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.confluent.kafka.schemaregistry.rules.PiiProto.Pii buildPartial() {
        io.confluent.kafka.schemaregistry.rules.PiiProto.Pii result = new io.confluent.kafka.schemaregistry.rules.PiiProto.Pii(this);
        result.pii_ = pii_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.confluent.kafka.schemaregistry.rules.PiiProto.Pii) {
          return mergeFrom((io.confluent.kafka.schemaregistry.rules.PiiProto.Pii)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.confluent.kafka.schemaregistry.rules.PiiProto.Pii other) {
        if (other == io.confluent.kafka.schemaregistry.rules.PiiProto.Pii.getDefaultInstance()) return this;
        if (!other.getPii().isEmpty()) {
          pii_ = other.pii_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                pii_ = input.readStringRequireUtf8();

                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private java.lang.Object pii_ = "";
      /**
       * <code>string pii = 1 [(.confluent.field_meta) = { ... }</code>
       * @return The pii.
       */
      public java.lang.String getPii() {
        java.lang.Object ref = pii_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          pii_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string pii = 1 [(.confluent.field_meta) = { ... }</code>
       * @return The bytes for pii.
       */
      public com.google.protobuf.ByteString
          getPiiBytes() {
        java.lang.Object ref = pii_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          pii_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string pii = 1 [(.confluent.field_meta) = { ... }</code>
       * @param value The pii to set.
       * @return This builder for chaining.
       */
      public Builder setPii(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        pii_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string pii = 1 [(.confluent.field_meta) = { ... }</code>
       * @return This builder for chaining.
       */
      public Builder clearPii() {
        
        pii_ = getDefaultInstance().getPii();
        onChanged();
        return this;
      }
      /**
       * <code>string pii = 1 [(.confluent.field_meta) = { ... }</code>
       * @param value The bytes for pii to set.
       * @return This builder for chaining.
       */
      public Builder setPiiBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        pii_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:io.confluent.kafka.schemaregistry.rules.Pii)
    }

    // @@protoc_insertion_point(class_scope:io.confluent.kafka.schemaregistry.rules.Pii)
    private static final io.confluent.kafka.schemaregistry.rules.PiiProto.Pii DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.confluent.kafka.schemaregistry.rules.PiiProto.Pii();
    }

    public static io.confluent.kafka.schemaregistry.rules.PiiProto.Pii getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Pii>
        PARSER = new com.google.protobuf.AbstractParser<Pii>() {
      @java.lang.Override
      public Pii parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Pii> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Pii> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.confluent.kafka.schemaregistry.rules.PiiProto.Pii getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_confluent_kafka_schemaregistry_rules_Pii_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_confluent_kafka_schemaregistry_rules_Pii_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tPii.proto\022\'io.confluent.kafka.schemare" +
      "gistry.rules\032\024confluent/meta.proto\"\034\n\003Pi" +
      "i\022\025\n\003pii\030\001 \001(\tB\010\202D\005\032\003PIIB5\n\'io.confluent" +
      ".kafka.schemaregistry.rulesB\010PiiProtoP\000b" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.confluent.protobuf.MetaProto.getDescriptor(),
        });
    internal_static_io_confluent_kafka_schemaregistry_rules_Pii_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_confluent_kafka_schemaregistry_rules_Pii_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_confluent_kafka_schemaregistry_rules_Pii_descriptor,
        new java.lang.String[] { "Pii", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(io.confluent.protobuf.MetaProto.fieldMeta);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    io.confluent.protobuf.MetaProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
