openapi: 3.0.1
info:
  title: Confluent Schema Registry
  version: v1
paths:
  /dek-registry/v1/keks/{name}/deks:
    get:
      summary: Get a list of dek scopes.
      operationId: getDekScopes_1
      parameters:
      - name: name
        in: path
        description: Name of the kek
        required: true
        schema:
          type: string
      - name: deleted
        in: query
        description: Whether to include deleted keys
        schema:
          type: boolean
      responses:
        default:
          description: default response
          content:
            application/vnd.schemaregistry.v1+json:
              schema:
                type: array
                items:
                  type: string
            application/vnd.schemaregistry+json; qs=0.9:
              schema:
                type: array
                items:
                  type: string
            application/json; qs=0.5:
              schema:
                type: array
                items:
                  type: string
    post:
      summary: Create a dek.
      operationId: createDek_1
      parameters:
      - name: name
        in: path
        description: Name of the kek
        required: true
        schema:
          type: string
      requestBody:
        description: The create request
        content:
          application/vnd.schemaregistry.v1+json:
            schema:
              $ref: '#/components/schemas/CreateDekRequest'
          application/vnd.schemaregistry+json:
            schema:
              $ref: '#/components/schemas/CreateDekRequest'
          application/json:
            schema:
              $ref: '#/components/schemas/CreateDekRequest'
          application/octet-stream:
            schema:
              $ref: '#/components/schemas/CreateDekRequest'
        required: true
      responses:
        "200":
          description: The create response
          content:
            application/vnd.schemaregistry.v1+json:
              schema:
                $ref: '#/components/schemas/Dek'
            application/vnd.schemaregistry+json; qs=0.9:
              schema:
                $ref: '#/components/schemas/Dek'
            application/json; qs=0.5:
              schema:
                $ref: '#/components/schemas/Dek'
  /dek-registry/v1/keks:
    get:
      summary: Get a list of kek names.
      operationId: getKekNames_1
      parameters:
      - name: deleted
        in: query
        description: Whether to include deleted keys
        schema:
          type: boolean
      responses:
        default:
          description: default response
          content:
            application/vnd.schemaregistry.v1+json:
              schema:
                type: array
                items:
                  type: string
            application/vnd.schemaregistry+json; qs=0.9:
              schema:
                type: array
                items:
                  type: string
            application/json; qs=0.5:
              schema:
                type: array
                items:
                  type: string
    post:
      summary: Create a kek.
      operationId: createKek_1
      requestBody:
        description: The create request
        content:
          application/vnd.schemaregistry.v1+json:
            schema:
              $ref: '#/components/schemas/CreateKekRequest'
          application/vnd.schemaregistry+json:
            schema:
              $ref: '#/components/schemas/CreateKekRequest'
          application/json:
            schema:
              $ref: '#/components/schemas/CreateKekRequest'
          application/octet-stream:
            schema:
              $ref: '#/components/schemas/CreateKekRequest'
        required: true
      responses:
        "200":
          description: The create response
          content:
            application/vnd.schemaregistry.v1+json:
              schema:
                $ref: '#/components/schemas/Kek'
            application/vnd.schemaregistry+json; qs=0.9:
              schema:
                $ref: '#/components/schemas/Kek'
            application/json; qs=0.5:
              schema:
                $ref: '#/components/schemas/Kek'
  /dek-registry/v1/keks/{name}:
    get:
      summary: Get a kek by name.
      operationId: getKek_1
      parameters:
      - name: name
        in: path
        description: Name of the kek
        required: true
        schema:
          type: string
      - name: deleted
        in: query
        description: Whether to include deleted keys
        schema:
          type: boolean
      responses:
        "200":
          description: The kek info
          content:
            application/vnd.schemaregistry.v1+json:
              schema:
                $ref: '#/components/schemas/Kek'
            application/vnd.schemaregistry+json; qs=0.9:
              schema:
                $ref: '#/components/schemas/Kek'
            application/json; qs=0.5:
              schema:
                $ref: '#/components/schemas/Kek'
        "404":
          description: Error code 40450 -- Key not found
    put:
      summary: Alters a kek.
      operationId: putKek_1
      parameters:
      - name: name
        in: path
        description: Name of the kek
        required: true
        schema:
          type: string
      requestBody:
        description: The update request
        content:
          application/vnd.schemaregistry.v1+json:
            schema:
              $ref: '#/components/schemas/UpdateKekRequest'
          application/vnd.schemaregistry+json:
            schema:
              $ref: '#/components/schemas/UpdateKekRequest'
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateKekRequest'
          application/octet-stream:
            schema:
              $ref: '#/components/schemas/UpdateKekRequest'
        required: true
      responses:
        "200":
          description: The update response
          content:
            application/vnd.schemaregistry.v1+json:
              schema:
                $ref: '#/components/schemas/Kek'
            application/vnd.schemaregistry+json; qs=0.9:
              schema:
                $ref: '#/components/schemas/Kek'
            application/json; qs=0.5:
              schema:
                $ref: '#/components/schemas/Kek'
        "404":
          description: Error code 40450 -- Key not found
    delete:
      summary: Delete a kek.
      operationId: deleteKek_1
      parameters:
      - name: name
        in: path
        description: Name of the kek
        required: true
        schema:
          type: string
      - name: permanent
        in: query
        description: Whether to perform a permanent delete
        schema:
          type: boolean
      responses:
        "204":
          description: No Content
        "404":
          description: Error code 40450 -- Key not found
  /dek-registry/v1/keks/{name}/deks/{scope}:
    get:
      summary: Get a dek by scope.
      operationId: getDek_1
      parameters:
      - name: name
        in: path
        description: Name of the kek
        required: true
        schema:
          type: string
      - name: scope
        in: path
        description: Scope of the dek
        required: true
        schema:
          type: string
      - name: algorithm
        in: query
        description: Algorithm of the dek
        schema:
          type: string
          enum:
          - AES128_GCM
          - AES256_GCM
          - AES256_SIV
      - name: deleted
        in: query
        description: Whether to include deleted keys
        schema:
          type: boolean
      responses:
        "200":
          description: The dek info
          content:
            application/vnd.schemaregistry.v1+json:
              schema:
                $ref: '#/components/schemas/Dek'
            application/vnd.schemaregistry+json; qs=0.9:
              schema:
                $ref: '#/components/schemas/Dek'
            application/json; qs=0.5:
              schema:
                $ref: '#/components/schemas/Dek'
        "404":
          description: Error code 40450 -- Key not found
    delete:
      summary: Delete a dek.
      operationId: deleteDek_1
      parameters:
      - name: name
        in: path
        description: Name of the kek
        required: true
        schema:
          type: string
      - name: scope
        in: path
        description: Scope of the dek
        required: true
        schema:
          type: string
      - name: algorithm
        in: query
        description: Algorithm of the dek
        schema:
          type: string
          enum:
          - AES128_GCM
          - AES256_GCM
          - AES256_SIV
      - name: permanent
        in: query
        description: Whether to perform a permanent delete
        schema:
          type: boolean
      responses:
        "204":
          description: No Content
        "404":
          description: Error code 40450 -- Key not found
components:
  schemas:
    Dek:
      type: object
      properties:
        kekName:
          type: string
        scope:
          type: string
        algorithm:
          type: string
          enum:
          - AES128_GCM
          - AES256_GCM
          - AES256_SIV
        encryptedKeyMaterial:
          type: string
        keyMaterial:
          type: string
    CreateDekRequest:
      type: object
      properties:
        kmsType:
          type: string
        kmsKeyId:
          type: string
        scope:
          type: string
        algorithm:
          type: string
          enum:
          - AES128_GCM
          - AES256_GCM
          - AES256_SIV
        encryptedKeyMaterial:
          type: string
        kmsKeyid:
          type: string
          writeOnly: true
    Kek:
      type: object
      properties:
        name:
          type: string
        kmsType:
          type: string
        kmsKeyId:
          type: string
        kmsProps:
          type: object
          additionalProperties:
            type: string
        doc:
          type: string
        shared:
          type: boolean
    CreateKekRequest:
      type: object
      properties:
        name:
          type: string
        kmsType:
          type: string
        kmsKeyId:
          type: string
        kmsProps:
          type: object
          additionalProperties:
            type: string
        doc:
          type: string
        shared:
          type: boolean
        kmsKeyid:
          type: string
          writeOnly: true
    UpdateKekRequest:
      type: object
      properties:
        kmsProps:
          type: object
          additionalProperties:
            type: string
        doc:
          type: string
        shared:
          type: boolean
