// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: metadata/v1/metadata.proto
// Protobuf Java Version: 4.29.3

package io.confluent.kafka.schemaregistry.storage.encoder;

public interface MetadataKeysetWrapperListOrBuilder extends
        // @@protoc_insertion_point(interface_extends:metadata.v1.MetadataKeysetWrapperList)
        com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.resourcemanager.meta.v1.ListMeta metadata = 1;</code>
   * @return Whether the metadata field is set.
   */
  boolean hasMetadata();
  /**
   * <code>.resourcemanager.meta.v1.ListMeta metadata = 1;</code>
   * @return The metadata.
   */
  io.confluent.resourcemanager.protobuf.apis.meta.v1.ListMeta getMetadata();
  /**
   * <code>.resourcemanager.meta.v1.ListMeta metadata = 1;</code>
   */
  io.confluent.resourcemanager.protobuf.apis.meta.v1.ListMetaOrBuilder getMetadataOrBuilder();

  /**
   * <code>repeated .metadata.v1.MetadataKeysetWrapper items = 2;</code>
   */
  java.util.List<io.confluent.kafka.schemaregistry.storage.encoder.MetadataKeysetWrapper>
  getItemsList();
  /**
   * <code>repeated .metadata.v1.MetadataKeysetWrapper items = 2;</code>
   */
  io.confluent.kafka.schemaregistry.storage.encoder.MetadataKeysetWrapper getItems(int index);
  /**
   * <code>repeated .metadata.v1.MetadataKeysetWrapper items = 2;</code>
   */
  int getItemsCount();
  /**
   * <code>repeated .metadata.v1.MetadataKeysetWrapper items = 2;</code>
   */
  java.util.List<? extends io.confluent.kafka.schemaregistry.storage.encoder.MetadataKeysetWrapperOrBuilder>
  getItemsOrBuilderList();
  /**
   * <code>repeated .metadata.v1.MetadataKeysetWrapper items = 2;</code>
   */
  io.confluent.kafka.schemaregistry.storage.encoder.MetadataKeysetWrapperOrBuilder getItemsOrBuilder(
          int index);
}
