// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: metadata/v1/metadata.proto
// Protobuf Java Version: 4.29.3

package io.confluent.kafka.schemaregistry.storage.encoder;

public final class Metadata {
  private Metadata() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
            com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
            /* major= */ 4,
            /* minor= */ 29,
            /* patch= */ 3,
            /* suffix= */ "",
            Metadata.class.getName());
  }
  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
            (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
          internal_static_metadata_v1_MetadataKeysetWrapper_descriptor;
  static final
  com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internal_static_metadata_v1_MetadataKeysetWrapper_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
          internal_static_metadata_v1_MetadataKeysetWrapperList_descriptor;
  static final
  com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internal_static_metadata_v1_MetadataKeysetWrapperList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
          internal_static_metadata_v1_MetadataKeysetWrapperSpec_descriptor;
  static final
  com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internal_static_metadata_v1_MetadataKeysetWrapperSpec_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
  getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
          descriptor;
  static {
    java.lang.String[] descriptorData = {
            "\n\032metadata/v1/metadata.proto\022\013metadata.v" +
                    "1\032\030apis/meta/v1/types.proto\"\204\001\n\025Metadata" +
                    "KeysetWrapper\0225\n\010metadata\030\001 \001(\0132#.resour" +
                    "cemanager.meta.v1.ObjectMeta\0224\n\004spec\030\002 \001" +
                    "(\0132&.metadata.v1.MetadataKeysetWrapperSp" +
                    "ec\"\203\001\n\031MetadataKeysetWrapperList\0223\n\010meta" +
                    "data\030\001 \001(\0132!.resourcemanager.meta.v1.Lis" +
                    "tMeta\0221\n\005items\030\002 \003(\0132\".metadata.v1.Metad" +
                    "ataKeysetWrapper\"O\n\031MetadataKeysetWrappe" +
                    "rSpec\022\031\n\021serialized_keyset\030\001 \001(\014\022\027\n\017rota" +
                    "tion_needed\030\002 \001(\010B5\n1io.confluent.kafka." +
                    "schemaregistry.storage.encoderP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
            .internalBuildGeneratedFileFrom(descriptorData,
                    new com.google.protobuf.Descriptors.FileDescriptor[] {
                            io.confluent.resourcemanager.protobuf.apis.meta.v1.Types.getDescriptor(),
                    });
    internal_static_metadata_v1_MetadataKeysetWrapper_descriptor =
            getDescriptor().getMessageTypes().get(0);
    internal_static_metadata_v1_MetadataKeysetWrapper_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
            internal_static_metadata_v1_MetadataKeysetWrapper_descriptor,
            new java.lang.String[] { "Metadata", "Spec", });
    internal_static_metadata_v1_MetadataKeysetWrapperList_descriptor =
            getDescriptor().getMessageTypes().get(1);
    internal_static_metadata_v1_MetadataKeysetWrapperList_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
            internal_static_metadata_v1_MetadataKeysetWrapperList_descriptor,
            new java.lang.String[] { "Metadata", "Items", });
    internal_static_metadata_v1_MetadataKeysetWrapperSpec_descriptor =
            getDescriptor().getMessageTypes().get(2);
    internal_static_metadata_v1_MetadataKeysetWrapperSpec_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
            internal_static_metadata_v1_MetadataKeysetWrapperSpec_descriptor,
            new java.lang.String[] { "SerializedKeyset", "RotationNeeded", });
    descriptor.resolveAllFeaturesImmutable();
    io.confluent.resourcemanager.protobuf.apis.meta.v1.Types.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
